baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'echo4eva'

[permalinks]
    blog = '/:filename/'

[menu]
    [[menu.main]]
        name = "blog"
        url = "/blog/"
    [[menu.main]]
        name = "portfolio"
        url = "/portfolio/"

[params]
    dateFormat = "Jan 2, 2006"

[taxonomies]
    tag = "tags"